### PR TITLE
Changes undercover detection chance to have a war level component

### PR DESCRIPTION
**Pull request by PoweredByPot**
Edited Summary:
Changes undercover detection to be based on aggression AND war level
Fixes a typo in resourcecheck.sqf
Fixes a minor spacing formatting issue

----------

simple spacing change for uniformity.

(actually just a simple test to make sure I got the process correct.)

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Process is indeed correct!

**Comment by PoweredByPot** [comment]
@Bob-Murphy apparently concurrent pull requests arent a thing?

**Comment by PoweredByPot** [comment]
I can remove the changes to NATOcrate.sqf if you want, but they really do belong, I promise.

**Comment by PoweredByPot** [comment]
also updated to fix an error in resourcecheck.sqf

**Pull request merged**
